### PR TITLE
Updated Codes

### PR DESCRIPTION
**Pull request by Yash-sudo-web**
Added an Alpha numeric password generator.

### CODE REVIEW

**Comment by ayush-799** [comment]
@Yash-sudo-web whatever u have updated it's not required, because when you run this program first time it will ask you for setup password and other times it will ask password to verify.
also there is no feature to regenerate password in your updates because once password is generated then when rerun the program then it will ask for "do you want to create a password "but it return always "No Problem thank you" irrespective of input (yes or no) in your update.
so if you can add a feature for change password with prev password authentication then i'll definitely merge it.

**Comment by ayush-799** [comment]
Screenshot at 2020-10-30 21-20-06
Screenshot at 2020-10-30 21-20-51

**Review by ayush-799 — COMMENTED** [review]
it is not required, because it is already there if you run this program first time it will ask you to set password and it also accepts alpha numeric char to generate password.

you can add a feature for change password with previous password authentication,

thanks

**Review by ayush-799 — CHANGES_REQUESTED** [review]
add change password feature

**Comment by Yash-sudo-web** [comment]
Ok Sir,I'll try, actually I am in standard 11, just started with Python.

**Comment by ayush-799** [comment]
> Ok Sir,I'll try, actually I am in standard 11, just started with Python.

keep it up dude, 
and no need to call me sir.

**Pull request closed without merging**
